// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "llm.baseURL": string;
      "llm.apiKey": string;
      "llm.modelName": string;
      "llm.temperature100": number;
      "llm.temperatureEnabled": boolean;
      "llm.maxTokens": number;
      "llm.streamUpdateSpeed": string;
      "chat.location": string;
      "chat.windowAlwaysOnTop": boolean;
      "sidepane.width": number;
      "sidepane.collapsed": boolean;
      "extend-selection-context": boolean;
      "extend-selection-size": number;
      "llm.providerConfigs": string;
      "llm.providerConfigsV2": string;
      "prompt.userPrompts": string;
      "llm.modelId": string;
      "chat.formulaOptimization": boolean;
      "chat.contextRounds": number;
      "chat.defaultMode": string;
      "chat.autoAttachItemData": boolean;
      "chat.openOnStartup": boolean;
      "chat.autoImagePrompt": boolean;
      "chat.thinkingEffort": string;
      "translate.enableAuto": boolean;
      "translate.extendContext": string;
      "translate.useAlternativeModel": boolean;
      "translate.modelId": string;
      "translate.targetLanguage": string;
      "translate.thinkingDepth": string;
      "imagePreview.location": string;
    };
  }
}
