// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "llm.baseURL": string;
      "llm.apiKey": string;
      "llm.modelName": string;
      "llm.temperature100": number;
      "llm.maxTokens": number;
      "llm.modelId": string;
      "extend-selection-context": boolean;
      "extend-selection-size": number;
      "llm.providerSettings": string;
    };
  }
}
